In [3]:
import numpy as np
import pandas as pd

- 1. Write a Pandas program to change the order of index of a given series.

In [4]:
data = np.random.rand(10)
ser = pd.Series(data,index=range(1,len(data)+1))
ser

1     0.626432
2     0.618280
3     0.093756
4     0.739138
5     0.450583
6     0.413881
7     0.862946
8     0.350825
9     0.517034
10    0.160202
dtype: float64

- 2. Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [5]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])
print('Addition')
print(s1+s2)
print('Subtraction')
print(s1-s2)
print('Multiplication')
print(s1*s2)
print('Division')
print(s1/s2)


Addition
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication
0     2
1    12
2    30
3    56
4    90
dtype: int64
Division
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


- 3. Write a Python program to convert a Pandas module Series to Python list and it's type

In [6]:
ser = pd.Series(np.random.randn(10))
x = list(ser.values)
x


[0.184881136083418,
 -0.3367139827134782,
 -0.30226136153366856,
 -0.6259341539103862,
 1.814208615780299,
 0.8336873257549894,
 -0.6851521694624412,
 -0.2991265018174127,
 0.6032203759288022,
 0.3916595970880258]

4. Write a Pandas program to select the rows where the score is missing, i.e. is NaN
   - Sample Python dictionary data and list labels:

exam_data = {'name': ['Sachin', 'Ganguly', 'Kohli', 'Johnson', 'Taylor',   
'Waugh', 'Yuvraj', 'Kambli', 'Srinath', 'Munaf'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 

In [7]:
exam_data = {'name': ['Sachin', 'Ganguly', 'Kohli', 'Johnson', 'Taylor',   'Waugh', 'Yuvraj', 'Kambli', 'Srinath', 'Munaf'],
            'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
            'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
            'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 
df = pd.DataFrame(exam_data,index=labels)
df[df['score'].isnull()]

name  score  attempts qualify
d  Johnson    NaN         3      no
h   Kambli    NaN         1      no

5. Write a Pandas program to create todays date

In [8]:
date = pd.datetime.today().date()
print(date)

2019-12-14


6.Write a Pandas program to create a Pivot table, by considering Titanic Dataset

7.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [11]:
np.array(np.arange(2,11).reshape(3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

8.Illustrate the difference between ravel and flatten by taking considering multidimensional array.

In [12]:
y = np.array(np.arange(9).reshape(3,3))
a = y.flatten()
b = y.ravel()
print('Original  :')
print(y,'\n')
print(a,'\n')
print(b,'\n')
y[0][2] = 999
print('Modified  : ')
print(y,'\n')
print(a,'\n')
print(b,'\n')


Original  :
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0 1 2 3 4 5 6 7 8] 

[0 1 2 3 4 5 6 7 8] 

Modified  : 
[[  0   1 999]
 [  3   4   5]
 [  6   7   8]] 

[0 1 2 3 4 5 6 7 8] 

[  0   1 999   3   4   5   6   7   8] 



9.Create a 3×3 numpyarray, find out the Minimum,Maximum values and also their indices accordingly for each axes. Also find out the Statistical methods such as Standard Deviation,Cumulative sum and product.

In [13]:
arr = np.array(np.arange(1,10).reshape(3,3))
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print('Row Max : ',arr.max(axis=0))
print('Indices : ',arr.argmax(axis=0))

Row Max :  [7 8 9]
Indices :  [2 2 2]


In [15]:
print('Column Max : ',arr.max(axis=1))
print('Indices : ',arr.argmax(axis=1))

Column Max :  [3 6 9]
Indices :  [2 2 2]


In [17]:
print('Standard Deviation : ',np.std(arr))
print('Cumulative Sum : ',arr.cumsum())

Standard Deviation :  2.581988897471611
Cumulative Sum :  [ 1  3  6 10 15 21 28 36 45]


In [18]:
print('Cumulative Product : ',arr.cumprod())

Cumulative Product :  [     1      2      6     24    120    720   5040  40320 362880]


10.Illustrate the concept of splitting by taking random positive values and also implementing different stacking methods on them.
